### ISSUE TITLE
Time Counter not working

### ISSUE THREAD

**Issue by kr-nahid** [knilch0r/freeshisen#12]
#### Expected behavior
it expceted that Time Counter works smoothly when i click on active/deactivate .

#### Actual behavior
Time Counter not working when i click on active/deactivate .

#### How to reproduce
* download the app
* open it
* start game then go to settings and deactivate Time Counter
* note the bug

> Browser/App version: 
 Operating system: android 5.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=ax3p2L11q2I

**Comment by knilch0r** [comment]
Thanks for your report!
This is, in fact, intentional (see [0:17](https://youtu.be/ax3p2L11q2I?t=17s) in the video) - changing the time counter settings is supposed to only take effect when a new game is started. The reason is that the counter isn't started at all if it's deactivated, so (re-)activating it in a running game would restart the time.
However, I concur that's not very "smooth". I guess it would be more intuitive if the time counter was always running, and the preferences would just make it (in)visible.
